language: php

php:
  - 5.5
  - 5.6

before_install:
  - wget -qO- http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
  - sudo add-apt-repository ppa:rethinkdb/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install rethinkdb -y

before_script:
  - sudo rethinkdb --daemon
  - composer self-update
  - composer install --dev --no-interaction
  - mkdir -p build/logs

script:
  - phpunit --coverage-clover build/logs/clover.xml
